(function(){
 const i18n={
  welcome:{zh:'你好！我是 AgentOS 的模擬 AI 顧問。先跟我聊聊你的生意吧：你主要賣什麼？平常怎麼接到客人的訂單？',en:'Hello! I am the AgentOS simulated AI advisor. Tell me about your business: what do you sell, and how do orders usually reach you?'},
  inquiry:{zh:'我理解你優先想解決分散的詢問、漏回覆與訂單整理。我會把「顧客詢問與訂單整理」列入初步方案。接下來，你也需要處理市集與線上庫存不同步嗎？',en:'I understand that scattered inquiries, missed replies, and order triage are the priority. I will include “Inquiry & Order Triage” in the draft plan. Do you also need help reconciling market and online inventory?'},
  inventory:{zh:'我理解市集銷售與線上紀錄不同步是主要困擾。我會把「庫存協調」列為確定性資料比對：它提出差異與更新建議，不會自行修改庫存。',en:'I understand that market sales and online records falling out of sync are the priority. I will include “Inventory Reconciliation” as deterministic comparison: it surfaces differences and update suggestions, but never changes stock by itself.'},
  control:{zh:'收到：庫存由你管理，所有對外訊息都必須先確認。我會把這些列為 Owner 邊界；任何建議都不會自動對外發送或更新庫存。',en:'Understood: you manage inventory, and every external message needs your approval. I will record these as Owner boundaries; no recommendation will send externally or update inventory automatically.'},
  ready:{zh:'目前已有足夠的示範資訊可形成初步診斷。你可以繼續補充，或查看我目前的理解。',en:'There is now enough demo information for an initial diagnosis. You can add more context or review my current understanding.'},
  unsupported:{zh:'這個 Demo 目前只示範顧客詢問／訂單整理與市集／線上庫存協調；我無法根據這段輸入產生有依據的建議。請選擇一個方向，或載入示範商家的回答。',en:'This demo currently covers customer inquiry/order triage and market/online inventory reconciliation only. I cannot make an evidence-grounded recommendation from that input. Choose a direction or load the sample merchant conversation.'},
  sample:{zh:'我經營手作黃銅飾品，市集賣完常沒立刻更新試算表；IG 和 LINE 的詢問也常漏回。庫存更新我自己管，對外訊息都要先讓我確認。',en:'I sell handmade brass accessories. Market sales are not always entered into my spreadsheet right away, and IG and LINE inquiries are easy to miss. I manage stock myself, and I must approve every external message.'},
  removeInventory:{zh:'了解，我會移除庫存協調，先只保留詢問與訂單整理。',en:'Understood. I will remove inventory reconciliation and keep only inquiry and order triage for now.'},
  onlyIg:{zh:'了解，我會聚焦 IG／LINE 示範訊息的整理，不會把庫存能力加入這次配置。',en:'Understood. I will focus on triaging the sample IG/LINE messages and will not include inventory capability in this configuration.'}
 };
 const initial=(lang='zh')=>({lang,screen:'onboard',setup:'conversation',signals:{inquiry:false,inventory:false,ownerReview:false},messages:[{role:'ai',key:'welcome'}],ready:false,proposalApproved:false,build:false,tested:false,active:false,operation:'idle',audit:[],toast:''});
 const audit={proposal:{id:'AUD-ONB-03',text:{zh:'Owner 已核准依對話形成的示範工作方案。',en:'Owner approved the demonstration work plan derived from the conversation.'}},build:{id:'AUD-ONB-04',text:{zh:'已完成可重現的模擬建置；未部署外部 Agent 或連接帳號。',en:'Repeatable simulated build completed; no external agent or account was deployed.'}},test:{id:'AUD-ONB-05',text:{zh:'選定能力的固定示範測試已通過；仍待 Owner 啟用。',en:'Frozen demonstration tests for selected capabilities passed; Owner activation is still required.'}},activate:{id:'AUD-ONB-06',text:{zh:'Owner 已啟用核准的示範工作流程。',en:'Owner activated the approved demonstration workflow.'}},reconfigure:{id:'AUD-ONB-07',text:{zh:'Owner 正在修改已啟用方案；舊的示範執行狀態已失效，須重新核准、測試與啟用。',en:'Owner is revising the enabled plan; the prior demonstration execution state is invalid and requires re-approval, testing, and activation.'}},conflict:{id:'AUD-OPS-01',text:{zh:'示範資料比對發現 BR-01 可用量可能不足；等待 Owner 決定。',en:'Synthetic comparison found possible BR-01 availability shortage; awaiting Owner decision.'}},approve:{id:'AUD-OPS-02',text:{zh:'Owner 核准更新示範庫存並保留 IG 訂單，待模擬執行。',en:'Owner approved synthetic inventory update and IG order hold; execution is pending.'}},execute:{id:'AUD-OPS-03',text:{zh:'已模擬完成試算表更新：BR-01 可用量為 1；未發送客戶訊息。',en:'Simulated spreadsheet update completed: BR-01 available quantity is 1; no customer message was sent.'}}};
 function plan(s){return {inquiry:!!s.signals.inquiry,inventory:!!s.signals.inventory,externalApproval:!!s.signals.ownerReview,manualInventory:!!s.signals.ownerReview};}
 function classify(text){let x=(text||'').toLowerCase(),r={};if(/不.*庫存|先不要.*庫存|不處理庫存|no inventory|without inventory/.test(x))r.removeInventory=true;else if(/庫存|市集|對帳|不同步|超賣|inventory|stock|market|reconcil/.test(x))r.inventory=true;if(/只.*ig|只做.*訊息|only ig|only.*message/.test(x))r.onlyIg=true;if(/詢問|回覆|訊息|訂單|ig|instagram|line|inquir|message|order|reply/.test(x))r.inquiry=true;if(/自己管|都要.*確認|所有.*確認|不.*自動|本人確認|manual|approve.*message|owner.*confirm/.test(x))r.ownerReview=true;return r}
 function replyKeys(intent){if(intent.removeInventory)return ['removeInventory'];if(intent.onlyIg)return intent.ownerReview?['onlyIg','control']:['onlyIg'];let out=[];if(intent.inquiry)out.push('inquiry');if(intent.inventory)out.push('inventory');if(intent.ownerReview)out.push('control');return out.length?out:['unsupported']}
 function addMessage(s,role,key,text){s.messages.push({role,key,text});}
 function reduce(s0,a){let s=JSON.parse(JSON.stringify(s0)),add=x=>s.audit.push(audit[x]);
  if(a&&a.type==='say'&&s.setup==='conversation'){let raw=(a.text||'').trim();if(!raw)return s;addMessage(s,'user','raw',raw);let q=classify(raw);if(q.removeInventory){s.signals.inventory=false;s.signals.inquiry=true}else if(q.onlyIg){s.signals.inquiry=true;s.signals.inventory=false}else{if(q.inquiry)s.signals.inquiry=true;if(q.inventory)s.signals.inventory=true}if(q.ownerReview)s.signals.ownerReview=true;replyKeys(q).forEach(key=>addMessage(s,'ai',key));if((s.signals.inquiry||s.signals.inventory)&&!s.ready){s.ready=true;addMessage(s,'ai','ready')}return s}
  if(a==='sampleConversation'&&s.setup==='conversation'){let raw=i18n.sample[s.lang];addMessage(s,'user','raw',raw);s.signals={inquiry:true,inventory:true,ownerReview:true};s.ready=true;addMessage(s,'ai','inquiry');addMessage(s,'ai','inventory');addMessage(s,'ai','control');addMessage(s,'ai','ready');return s}
  if(a==='reviewPlan'&&s.setup==='conversation'&&(s.signals.inquiry||s.signals.inventory)){s.setup='review';return s}
  if(a==='backToChat'&&s.setup==='review'){s.setup='conversation';return s}
  if(a==='editPlan'){s.setup='conversation';s.proposalApproved=false;s.build=false;s.tested=false;s.active=false;s.operation='idle';s.toast='';add('reconfigure');return s}
  if(a==='approveProposal'&&s.setup==='review'&&(s.signals.inquiry||s.signals.inventory)){s.proposalApproved=true;s.setup='build';add('proposal');return s}
  if(a==='build'&&s.setup==='build'&&s.proposalApproved){s.build=true;add('build');return s}
  if(a==='test'&&s.setup==='build'&&s.build){s.tested=true;add('test');return s}
  if(a==='activate'&&s.setup==='build'&&s.tested){s.active=true;add('activate');s.screen='mission';s.toast='activated';return s}
  if(a==='startOperation'&&s.active&&s.operation==='idle'){let p=plan(s);if(p.inquiry)s.operation='triage';else if(p.inventory)s.operation='inventory_ready';return s}
  if(a==='detectConflict'&&s.active&&['triage','inventory_ready'].includes(s.operation)&&plan(s).inventory){s.operation='owner_pending';add('conflict');return s}
  if(a==='approveOperation'&&s.operation==='owner_pending'){s.operation='approved_pending';add('approve');return s}
  if(a==='executeOperation'&&s.operation==='approved_pending'){s.operation='executed';add('execute');return s}
  if(a==='clearToast'){s.toast='';return s}return s}
 const costs=s=>{const op=['owner_pending','approved_pending','executed'].includes(s.operation)?12:0;return {revenue:2720,material:960,marketFee:240,simulatedOps:op,contribution:2720-960-240-op,pendingValue:1360}};
 window.AGENTOS_CORE={initial,reduce,costs,plan,i18n,classify};
})();
